apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: fastapi
    image: my-fastapi-image:latest
    ports:
    - containerPort: 8000
      hostPort: 8000
    - containerPort: 22
      hostPort: 2222
    volumeMounts:
    - name: app-volume
      mountPath: /app
  - name: couchdb
    image: couchdb:latest
    env:
    - name: COUCHDB_USER
      value: "admin"
    - name: COUCHDB_PASSWORD
      value: "password"
    volumeMounts:
    - name: couchdb-volume
      mountPath: /opt/couchdb/data
  volumes:
  - name: app-volume
    hostPath:
      path: $HOME/Code/Containers/fastapi-couchdb-template/app
  - name: couchdb-volume
    hostPath:
      path: $HOME/Code/Containers/fastapi-couchdb-template/couchdb
